# Add 'repo' label to any root file changes
repo:
  - ./**/*

# Add 'test' label to any change to test files within the source/test dir
test:
  - src/test/*

# Add 'source' label to any change to src files within the source dir EXCEPT for the docs sub-folder
source:
  - src/**/*
